/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static String getMessage() {
        return "Hello from CodeAlpha Gradle Application!";
    }

    public static void main(String[] args) {
        System.out.println(getMessage());
    }
}