/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {

    @Test
    void messageShouldBeCorrect() {
        assertEquals(
            "Hello from CodeAlpha Gradle Application!",
            App.getMessage()
        );
    }
}